### ISSUE TITLE
remove scrollbar css for mobile

### ISSUE THREAD

**Issue by oeyoews** [tiddly-gittly/TiddlyWiki-Chinese-Tutorial#45]

**Comment by linonetwo** [comment]
哪个插件影响的？是我的itonnote主题吗

**Comment by oeyoews** [comment]
对， 大概是后来添加的那个scrollbar样式

**Comment by linonetwo** [comment]
有空指一下要改哪里，得到 https://github.com/tiddly-gittly/tiddlywiki-plugins/tree/master/themes/linonetwo/itonnote 改了
