### ISSUE TITLE
想请教下，首页弹窗提示是哪个插件实现的？

### ISSUE THREAD

**Issue by Juijote** [tiddly-gittly/TiddlyWiki-Chinese-Tutorial#49]
翻了一遍插件好像不太对，找不到😂。

**Comment by oeyoews** [comment]
没有插件，wikitext写的

**Comment by linonetwo** [comment]
哪个弹窗提示啊

**Comment by Juijote** [comment]
> 哪个弹窗提示啊

就是欢迎提示窗，一直不知道该怎么实现😂。

**Comment by oeyoews** [comment]
![Uploading 89DAE07E-5459-4ECE-A24E-BE9994D71852.png…]()  应该是这个吧， 涉及到的东西有点多，主要是用到了tm-modal,可以看上面我提到的那个commit

**Comment by Juijote** [comment]
> @Juijote 应该是这个吧， 涉及到的东西有点多，主要是用到了tm-modal,可以看上面我提到的那个commit

在看舞翻译的官方文档，是用到了启动加载和交互窗口这两样吗？

**Comment by oeyoews** [comment]
> > @Juijote 应该是这个吧， 涉及到的东西有点多，主要是用到了tm-modal,可以看上面我提到的那个commit
> 
> 在看舞翻译的官方文档，是用到了启动加载和交互窗口这两样吗？

对的

**Comment by Juijote** [comment]
> > > @Juijote 应该是这个吧， 涉及到的东西有点多，主要是用到了tm-modal,可以看上面我提到的那个commit
> > 
> > 
> > 在看舞翻译的官方文档，是用到了启动加载和交互窗口这两样吗？
> 
> 对的，还用到了延迟触发，设置的是在线触发，本地不显示，比较友好

非常感谢，已经实现了，官方文档藏得比较深，之前没留意就漏过了。
