### ISSUE TITLE
申请加入贡献团队似乎失效。

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TiddlyWiki-Chinese-Tutorial#53]
Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by FSpark** [comment]
@linonetwo 申请入口确实挂了

**Comment by Zacharia2** [comment]
> 已经看见你在 chinese-tutorial Team 里了呀，另外好像在群里找不着你了？😥

嗯嗯，主要是太占用注意力了，时不时就像看看群消息，都成习惯了哈哈哈😁，所以想放空一段时间，休息休息，在回去。

**Comment by FSpark** [comment]
@Zacharia2  好的，随时欢迎回来 😂
