### ISSUE TITLE
会支持导入evernote的enex格式吗

### ISSUE THREAD

**Issue by kunpeng9** [tiddly-gittly/TiddlyWiki-Chinese-Tutorial#70]
evernote更新太不给力了、而且客户端太卡、数据库太大了=默认在C盘，我电脑那个图标又深红色了
想把导出的enex导入太微
葫芦笔记、romaedit、logseq、ob等都不好导入印象笔记，要那个啥代码来着，搞忘记了，之前看过1点

**Comment by linonetwo** [comment]
你试试官方插件，有效果了记得写个教程

**Comment by dongrentianyu** [comment]
有个测试文件就好了。我也没用过evernote。

**Comment by linonetwo** [comment]
我已经用那个插件把印象笔记完全导入太微了。需要注意手动改一下导入用的工具，参考 https://github.com/vzhd1701/evernote-backup/pull/54

**Comment by linonetwo** [comment]
主要是不用这个工具，不改它的话，默认导出的 enex 会丢图片，印象笔记的锅。
