### ISSUE TITLE
更新一个宏

### ISSUE THREAD

**Issue by MeizhouWan** [tiddly-gittly/TiddlyWiki-Chinese-Tutorial#72]
请求撤销鼠标悬停提示
此外，增加鼠标悬停嵌入

$:/plugins/my/Mouse Hover Embed
$:/tags/Macro

\define mhe(_)
<span style="border-bottom: 1px dashed; cursor: help;" title= {{$_$}}>$_$</span>
\end

相比之前，好处有
减少了一个参数，引用了嵌入，也能修改嵌入条目。

缺点
嵌入条目正文似乎不能有任意语法。当别的条目用这宏之后，悬停内容会出现语法代码，不美观。

效果：节省卡片空间，嵌入化为名称。

**Comment by linonetwo** [comment]
没看懂，截个图看看，还有鼠标悬停提示是说那个 preview glass 插件吗

**Comment by MeizhouWan** [comment]
撤下“鼠标悬停提示”这宏。
github发不了图

太微爱好QQ群多次艾特你，

**Comment by linonetwo** [comment]
不知道你说的是哪个，图拖上来就好了。

我比较忙，你可以at别的热心群友
