### ISSUE TITLE
教程使用markdown进行编写

### ISSUE THREAD

**Issue by oeyoews** [tiddly-gittly/TiddlyWiki-Chinese-Tutorial#78]
* 使用markdown有利于更多人更快更好的维护编辑教程
* 可以使用不同的markdown编辑器单独编辑
* 有利于搬运
* ...

**Comment by linonetwo** [comment]
我觉得可以，不过现在要配置新建子条目默认创建md还是有点麻烦的，我是打算等核心更新 https://github.com/Jermolene/TiddlyWiki5/discussions/7684#discussioncomment-6791067 ，这样我们啥也不用改

单你能先配按钮配出来的话，你可以先配上去，不然得等一两年才会有

**Comment by linonetwo** [comment]
不过其实主要还是  可以使用不同的markdown编辑器单独编辑

别的都可以一键导出，例如做个按钮导出md到剪贴板什么的

**Comment by Gk0Wk** [comment]
tw是以插件形式支持的md，新人可能不知道怎么搞，只能看到源码
