### ISSUE TITLE
唯一的入口/信息流：聚集教程、翻译、样例等等

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TiddlyWiki-Chinese-Tutorial#79]
就像obsidian的官网、GitHub、或者其他内容丰富的网站，只需要记住一个网址，其它有趣的内容都可以在该网站发现。

**Comment by linonetwo** [comment]
太记就是 tidgi.fun 不过只打算放太记内置插件的简单用法，更多用法还是会链接到中文教程等等
